# Generated by Django 3.0.8 on 2020-07-30 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20200730_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
