# Generated by Django 3.0.8 on 2020-07-30 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auto_20200730_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.ForeignKey(default=5, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='auctions.Category'),
        ),
    ]
