# Generated by Django 3.0.8 on 2020-07-31 09:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20200731_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='item',
            field=models.ManyToManyField(related_name='watchers', to='auctions.Listing'),
        ),
        migrations.AddField(
            model_name='watch',
            name='user',
            field=models.ManyToManyField(related_name='watchlist', to=settings.AUTH_USER_MODEL),
        ),
    ]
