# Generated by Django 3.0.8 on 2020-08-02 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_auto_20200731_0953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['bid']},
        ),
    ]
